# This is what an example config would look like.
# You can choose your own account names and add as many accounts as you want.
# Account names are case insensitive.

[personal]
username = your-personal-username
name = Your Personal Commit Name
email = 123456+your-personal-username@users.noreply.github.com
allowed_emails =
    personal@example.com

[school]
username = your-school-username
name = Your School Commit Name
email = 789012+your-school-username@users.noreply.github.com
allowed_emails =
    student@example.edu

[work]
username = your-work-username
name = Your Work Commit Name
email = work@example.com
allowed_emails =
    345678+your-work-username@users.noreply.github.com
