use super::{optional_config, run};
use crate::utils::output;
use anyhow::{Context, Result};
use std::{env, path::PathBuf};

pub fn value(key: &str) -> Result<String> {
    Ok(optional_config(&["config", "--global", "--get", key])?.unwrap_or_default())
}

pub struct Writer<'a> {
    command: &'a str,
    changed: bool,
    reported: bool,
}

impl Writer<'_> {
    pub(super) fn comment(&self) -> String {
        format!("Generated by multigh ({})", self.command)
    }

    pub fn edit(&mut self, args: &[&str]) -> Result<()> {
        let comment = self.comment();
        let mut options = vec!["config", "--global"];

        if !args.contains(&"--unset-all") {
            options.extend(["--comment", &comment]);
        }

        options.extend(args);
        run(&options)?;
        self.changed = true;

        Ok(())
    }

    pub fn set(&mut self, key: &str, value: &str) -> Result<()> {
        if optional_config(&["config", "--global", "--null", "--get-all", key])?.as_deref()
            == Some(&format!("{value}\0"))
        {
            return Ok(());
        }

        self.edit(&[key, value])
    }

    pub fn report(&mut self) {
        if self.reported {
            return;
        }

        output::section(&if self.changed {
            format!("✓ Global Git config updated by {}", self.command)
        } else {
            "Global Git config unchanged".to_owned()
        });
        println!();
        self.reported = true;
    }

    pub fn suppress_report(&mut self) {
        self.reported = true;
    }
}

pub fn update<T>(command: &str, update: impl FnOnce(&mut Writer<'_>) -> Result<T>) -> Result<T> {
    let mut global = Writer {
        command,
        changed: false,
        reported: false,
    };
    let result = update(&mut global);

    if global.changed || result.is_ok() {
        global.report();
    }

    result
}

pub fn path() -> Result<PathBuf> {
    let entries = run(&[
        "config",
        "--global",
        "--no-includes",
        "--show-origin",
        "--null",
        "--list",
    ])?;
    let path = entries
        .split('\0')
        .next()
        .and_then(|origin| origin.strip_prefix("file:"))
        .context("Git did not report a global config filepath")?;

    Ok(env::current_dir()?.join(path))
}
