use crate::support::{IDENTITIES, Sandbox};
use std::fs;

#[test]
fn setup_labels_generated_settings_and_reports_only_actual_global_changes() {
    let sandbox = Sandbox::new();
    let original = fs::read_to_string(sandbox.path("gitconfig")).unwrap();
    let output = sandbox.ok("mgh", &["setup"]);
    let generated = fs::read_to_string(sandbox.path("gitconfig")).unwrap();

    assert!(generated.starts_with(&original));
    assert_eq!(
        generated
            .matches("# Generated by multigh (mgh setup)")
            .count(),
        7
    );
    assert_eq!(output.matches("Global Git config updated").count(), 1);

    for identity_name in ["personal", "school"] {
        let identity = fs::read_to_string(sandbox.path(&format!(
            "state/multigh/identities/git-{identity_name}.conf"
        )))
        .unwrap();

        assert_eq!(
            identity
                .matches("# Generated by multigh (mgh setup)")
                .count(),
            2
        );
    }

    let repeated = sandbox.ok("mgh", &["setup"]);

    assert!(!repeated.contains("Global Git config updated"));
    assert_eq!(repeated.matches("Global Git config unchanged").count(), 1);
    assert_eq!(
        generated,
        fs::read_to_string(sandbox.path("gitconfig")).unwrap()
    );
}

#[test]
fn switching_labels_changed_defaults_with_the_generating_command() {
    let sandbox = Sandbox::new();
    let output = sandbox.ok("mgh", &["switch", "PERSONAL"]);
    let generated = fs::read_to_string(sandbox.path("gitconfig")).unwrap();

    assert_eq!(output.matches("Global Git config updated").count(), 1);
    assert_eq!(
        generated
            .matches("# Generated by multigh (mgh switch PERSONAL)")
            .count(),
        8
    );
    assert!(generated.contains("defaultBranch = main"));

    let repeated = sandbox.ok("mgh", &["switch", "personal"]);

    assert!(!repeated.contains("Global Git config updated"));
    assert_eq!(repeated.matches("Global Git config unchanged").count(), 1);
    assert_eq!(
        generated,
        fs::read_to_string(sandbox.path("gitconfig")).unwrap()
    );
}

#[test]
fn enabling_protections_labels_the_hook_setting_and_preserves_other_settings() {
    let sandbox = Sandbox::new();
    let original = fs::read_to_string(sandbox.path("gitconfig")).unwrap();
    let output = sandbox.ok("mgh", &["repo", "protections", "on"]);
    let generated = fs::read_to_string(sandbox.path("gitconfig")).unwrap();

    assert!(generated.starts_with(&original));
    assert_eq!(
        generated
            .matches("# Generated by multigh (mgh repo protections on)")
            .count(),
        1
    );
    assert_eq!(output.matches("Global Git config updated").count(), 1);

    let repeated = sandbox.ok("mgh", &["repo", "protections", "on"]);

    assert!(!repeated.contains("Global Git config updated"));
    assert_eq!(repeated.matches("Global Git config unchanged").count(), 1);
    assert_eq!(
        generated,
        fs::read_to_string(sandbox.path("gitconfig")).unwrap()
    );
}

#[test]
fn removing_obsolete_identity_rules_reports_a_change_without_leaving_comments() {
    let sandbox = Sandbox::new();

    sandbox.ok("mgh", &["setup"]);
    sandbox.write(
        "config/multigh/identities.jsonc",
        r#"{"personal": {"username": "alice", "commit": {"email": "alice@example.com", "name": "Alice Example"}}}"#,
    );

    let output = sandbox.ok("mgh", &["setup"]);
    let generated = fs::read_to_string(sandbox.path("gitconfig")).unwrap();

    assert_eq!(output.matches("Global Git config updated").count(), 1);
    assert!(!generated.contains("bob/**") && !generated.contains("git-school.conf"));
    assert_eq!(
        generated
            .matches("# Generated by multigh (mgh setup)")
            .count(),
        4
    );
}

#[test]
fn git_config_overrides_and_symlinks_keep_their_original_locations() {
    let sandbox = Sandbox::new();
    let original = fs::read_to_string(sandbox.path("gitconfig")).unwrap();

    sandbox.write("custom.conf", &original);
    std::os::unix::fs::symlink(sandbox.path("custom.conf"), sandbox.path("config-link")).unwrap();

    let output = sandbox
        .command("mgh")
        .env("GIT_CONFIG_GLOBAL", sandbox.path("config-link"))
        .arg("setup")
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(String::from_utf8_lossy(&output.stdout).contains("Global Git config updated"));
    assert!(String::from_utf8_lossy(&output.stdout).contains(&format!(
        "  Git config                  {}",
        sandbox.path("config-link").display()
    )));
    assert!(
        fs::symlink_metadata(sandbox.path("config-link"))
            .unwrap()
            .file_type()
            .is_symlink()
    );
    assert!(
        fs::read_to_string(sandbox.path("custom.conf"))
            .unwrap()
            .contains("# Generated by multigh (mgh setup)")
    );
    assert_eq!(
        original,
        fs::read_to_string(sandbox.path("gitconfig")).unwrap()
    );
}

#[test]
fn completed_config_changes_are_reported_even_if_authentication_switching_fails() {
    let sandbox = Sandbox::new();

    sandbox.write("fail-switch", "");

    let output = sandbox.run("mgh", &["switch", "personal"]);
    let generated = fs::read_to_string(sandbox.path("gitconfig")).unwrap();

    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("gh:"));
    assert_eq!(
        String::from_utf8_lossy(&output.stdout)
            .matches("Global Git config updated")
            .count(),
        1
    );
    assert_eq!(
        generated
            .matches("# Generated by multigh (mgh switch personal)")
            .count(),
        6
    );
    assert_eq!(
        sandbox
            .ok("git", &["config", "--global", "user.email"])
            .trim(),
        "bob@example.edu"
    );
}

#[test]
fn setup_reports_unchanged_global_config_when_only_identity_files_change() {
    let sandbox = Sandbox::new();

    sandbox.ok("mgh", &["setup"]);

    let before = fs::read(sandbox.path("gitconfig")).unwrap();

    sandbox.write(
        "config/multigh/identities.jsonc",
        &IDENTITIES.replace("alice@example.com", "new@example.com"),
    );

    let output = sandbox.ok("mgh", &["setup"]);

    assert_eq!(output.matches("Global Git config unchanged").count(), 1);
    assert!(!output.contains("Global Git config updated"));
    assert_eq!(before, fs::read(sandbox.path("gitconfig")).unwrap());
    assert_eq!(
        sandbox.ok("git", &["config", "user.email"]).trim(),
        "new@example.com"
    );
}

#[test]
fn failed_commands_do_not_claim_successful_unchanged_configuration() {
    let sandbox = Sandbox::new();

    sandbox.ok("mgh", &["setup"]);
    sandbox.write("fail-switch", "");

    let before = fs::read(sandbox.path("gitconfig")).unwrap();
    let output = sandbox.run("mgh", &["switch", "personal"]);
    let text = String::from_utf8_lossy(&output.stdout);

    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("gh:"));
    assert!(!text.contains("Global Git config unchanged"));
    assert!(!text.contains("Global Git config updated"));
    assert_eq!(before, fs::read(sandbox.path("gitconfig")).unwrap());
}
