use crate::{
    config::{self, Config},
    output, process,
};
use anyhow::{Context, Result, ensure};
use std::{
    collections::BTreeMap,
    env, fs,
    path::{Path, PathBuf},
};
use tempfile::NamedTempFile;

pub fn run(args: &[&str]) -> Result<String> {
    process::run("git", args)
}

pub fn optional(args: &[&str]) -> Result<Option<String>> {
    process::optional("git", args)
}

pub fn value(key: &str) -> Result<Option<String>> {
    optional(&["config", "--get", key])
}

pub fn local(key: &str) -> Result<Option<String>> {
    optional(&["config", "--local", "--get", key])
}

pub fn global(key: &str) -> Result<String> {
    Ok(optional(&["config", "--global", "--get", key])?.unwrap_or_default())
}

pub fn set(scope: &str, key: &str, value: &str) -> Result<()> {
    run(&["config", scope, key, value])?;

    Ok(())
}

pub struct GlobalConfig<'a> {
    command: &'a str,
    changed: bool,
    reported: bool,
}

impl GlobalConfig<'_> {
    fn comment(&self) -> String {
        format!("Generated by multigh ({})", self.command)
    }

    pub fn edit(&mut self, args: &[&str]) -> Result<()> {
        let comment = self.comment();
        let mut options = vec!["config", "--global"];

        if !args.contains(&"--unset-all") {
            options.extend(["--comment", &comment]);
        }

        options.extend(args);
        run(&options)?;
        self.changed = true;

        Ok(())
    }

    pub fn set(&mut self, key: &str, value: &str) -> Result<()> {
        if optional(&["config", "--global", "--null", "--get-all", key])?.as_deref()
            == Some(&format!("{value}\0"))
        {
            return Ok(());
        }

        self.edit(&[key, value])
    }

    pub fn report(&mut self) {
        if self.reported {
            return;
        }

        output::section(&if self.changed {
            format!("✓ Global Git config updated by {}", self.command)
        } else {
            "Global Git config unchanged".to_owned()
        });
        println!();
        self.reported = true;
    }
}

pub fn update_global<T>(
    command: &str,
    update: impl FnOnce(&mut GlobalConfig<'_>) -> Result<T>,
) -> Result<T> {
    let mut global = GlobalConfig {
        command,
        changed: false,
        reported: false,
    };
    let result = update(&mut global);

    if global.changed || result.is_ok() {
        global.report();
    }

    result
}

pub fn global_path() -> Result<PathBuf> {
    let entries = run(&[
        "config",
        "--global",
        "--no-includes",
        "--show-origin",
        "--null",
        "--list",
    ])?;
    let path = entries
        .split('\0')
        .next()
        .and_then(|origin| origin.strip_prefix("file:"))
        .context("Git did not report a global config filepath")?;

    Ok(env::current_dir()?.join(path))
}

pub fn entries(scope: Option<&str>, pattern: &str) -> Result<BTreeMap<String, Vec<String>>> {
    let mut args = vec!["config"];

    if let Some(scope) = scope {
        args.push(scope);
    }

    args.extend(["--null", "--get-regexp", pattern]);

    let mut values: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for entry in optional(&args)?.unwrap_or_default().split('\0') {
        if let Some((key, value)) = entry.split_once('\n') {
            values
                .entry(key.to_owned())
                .or_default()
                .push(value.to_owned());
        }
    }

    Ok(values)
}

pub fn private(path: &Path, directory: bool) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;

        fs::set_permissions(
            path,
            fs::Permissions::from_mode(if directory { 0o700 } else { 0o600 }),
        )?;
    }

    #[cfg(not(unix))]
    let _ = (path, directory);

    Ok(())
}

pub fn identity_directory() -> Result<PathBuf> {
    Ok(config::directory("XDG_STATE_HOME", ".local/state")?.join("multigh/identities"))
}

pub fn setup_identities(config: &Config, global: &mut GlobalConfig<'_>) -> Result<PathBuf> {
    let directory = identity_directory()?;
    let previous = entries(Some("--global"), "^[iI]nclude[iI]f\\.")?;
    let mut desired = BTreeMap::new();

    for (alias, account) in &config.accounts {
        let identity = directory.join(format!("git-{alias}.conf"));

        ensure!(
            !fs::symlink_metadata(&identity)
                .is_ok_and(|metadata| metadata.file_type().is_symlink()),
            "Identity file is a symlink: {}",
            identity.display()
        );

        for prefix in [
            "https://github.com/",
            "git@github.com:",
            "ssh://git@github.com/",
        ] {
            let key = format!(
                "includeif.hasconfig:remote.*.url:{prefix}{}/**.path",
                account.username
            );

            ensure!(
                previous.get(&key).is_none_or(|values| values
                    .iter()
                    .all(|value| Path::new(value).parent() == Some(directory.as_path()))),
                "Existing Git identity rule conflicts with [{alias}]; no rules changed"
            );

            desired.insert(key, identity.clone());
        }
    }

    fs::create_dir_all(&directory)?;
    private(&directory, true)?;

    for (alias, account) in &config.accounts {
        let temporary = NamedTempFile::new_in(&directory)?;
        let path = temporary.path().to_string_lossy();

        let comment = global.comment();

        for (key, value) in [("user.name", &account.name), ("user.email", &account.email)] {
            run(&["config", "--file", &path, "--comment", &comment, key, value])?;
        }

        temporary.persist(directory.join(format!("git-{alias}.conf")))?;
    }

    for (key, values) in &previous {
        if desired
            .get(key)
            .is_some_and(|identity| values.as_slice() == [identity.to_string_lossy().as_ref()])
        {
            continue;
        }

        for value in values.iter().collect::<std::collections::BTreeSet<_>>() {
            if Path::new(&value).parent() == Some(directory.as_path()) {
                global.edit(&["--fixed-value", "--unset-all", key, value])?;
            }
        }
    }

    for (key, identity) in desired {
        if previous
            .get(&key)
            .is_some_and(|values| values.as_slice() == [identity.to_string_lossy().as_ref()])
        {
            continue;
        }

        global.edit(&["--add", &key, &identity.to_string_lossy()])?;
    }

    Ok(directory)
}
